name: Deploy to Fly.io

on:
  push:
    branches: [main]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: superfly/flyctl-actions/setup-flyctl@1e21c5825087a0d1578c4b1a71a0ef181b863e37 # master pinned

      - run: flyctl deploy --remote-only
